#[Deployment][@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@]
# [From](https://k8s.io/examples/application/deployment.yaml)
apiVersion: apps/v1 # apps/v1beta2 版本
kind: Deployment
metadata:
  name: logstash-deployment
  namespace: coam-dev-elk-ns
spec:
  selector:
    matchLabels:
      app: us-logstash
      version: v-0.0.2
  replicas: 1 # 副本集数量
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: us-logstash
        version: v-0.0.2
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      # 直接通过节点名称调度到指定节点 - [Pod调度到指定Node](https://blog.csdn.net/u013201439/article/details/79436465)
      nodeName: t.cs.2
      #使用主机网络 - 暴露端口:500,4500- 不推荐 -- 不能开启,已使用 `hostPort` 暴露主机端口,否则开启端口监听将导致集群崩溃!!!
      #hostNetwork: true
      containers:
        - name: us-logstash
          image: registry.ioros.com/coam/us.elk.logstash:0.0.2
          env:
            - name: COAM-SSH-NODE-PORT
              value: "32005"
          # Just sleep forever
          #command: ["sleep"]
          #args: ["infinity"]
          command: ["/opt/data/elk/logstash/bin/logstash"]
          args: []
          terminationMessagePath: /var/log/kubernetes/termination/pods.log
          ports:
            - containerPort: 22222
              protocol: TCP
            - containerPort: 9600
              protocol: TCP
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            privileged: true
          lifecycle:
            postStart:
              exec:
                # start ssh service...
                command: ["/bin/sh", "-c", "/usr/sbin/sshd -f ~/.ssh/server/etc/sshd_config"]
                #command: ["/bin/sh", "-c", "echo ..."]
          volumeMounts:
            - mountPath: /etc/ssl/coam
              name: etc-ssl-coam-volume
            - name: data-opt-elk-logstash-config-volume
              mountPath: /opt/data/elk/logstash/config
            #- name: data-home-coam-volume
            #  mountPath: /data/home/coam
            - name: var-log-logstash-volume
              mountPath: /var/log/logstash
      volumes:
        - name: etc-ssl-coam-volume
          hostPath:
            # directory location on host
            path: /etc/ssl/coam
            # this field is optional
            type: Directory
        - name: data-home-coam-volume
          hostPath:
            # directory location on host
            path: /data/home/coam
            # this field is optional
            type: Directory
        - name: data-opt-elk-logstash-config-volume
          hostPath:
            # directory location on host
            path: /opt/data/elk/logstash/config
            # this field is optional
            type: Directory
        - name: var-log-logstash-volume
          hostPath:
            # directory location on host
            path: /var/log/logstash
            # this field is optional
            type: DirectoryOrCreate

---
#[Service][@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@]
# [From](https://kubernetes.io/zh/docs/concepts/services-networking/connect-applications-service/)
apiVersion: v1
kind: Service
metadata:
  name: us-logstash
  namespace: coam-dev-elk-ns
  labels:
    app: us-logstash
    version: v-0.0.2
spec:
  #type: NodePort
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  ports:
    # SSH 端口
    - name: tcp-isp-logstash-22222
      protocol: TCP
      port: 22000
      targetPort: 22222
      nodePort: 32005
    - name: tcp-isp-logstash-9600
      protocol: TCP
      port: 9600
      targetPort: 9600
      #nodePort: 9600
  selector:
    app: us-logstash
    version: v-0.0.2
  sessionAffinity: None

#[Ended][@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@]