# [From](https://imroc.io/posts/kubernetes/let-ingress-enable-free-https-with-cert-manager/)
#[](https://crt.sh/?q=%pyios.com)
apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: zyf@iirii.com

    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-prod

    http01: {}