# [From](https://cert-manager.readthedocs.io/en/latest/tutorials/acme/dns-validation.html)
#[](https://crt.sh/?q=%pyios.com)
apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: zyf@iirii.com

    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-staging

    http01: {}