#[kubernetes跨namespace访问服务](http://yizhanggou.top/kubernetes%E8%B7%A8namespace%E8%AE%BF%E9%97%AE%E6%9C%8D%E5%8A%A1/)
#[在kubernets中不同命名空间的服务相互访问](https://johng.cn/services-communication-in-different-namespaces-in-kubernets/)
apiVersion: v1
kind: Service
metadata:
  name: us-nginx
  namespace: ingress-nginx
spec:
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31080
      protocol: TCP
      name: http
    - port: 8843
      targetPort: 8843
      nodePort: 31443
      protocol: TCP
      name: https
  sessionAffinity: None
  type: ExternalName
  externalName: us-nginx.default.svc.cluster.local