apiVersion: v1
kind: Service
metadata:
  name: flaskapp
  labels:
    app: flaskapp
    version: v1
spec:
  selector:
    app: flaskapp
    version: v1
  ports:
    - name: http
      port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskapp
spec:
  selector:
    matchLabels:
      app: flaskapp
  replicas: 1
  template:
    metadata:
      labels:
        app: flaskapp
        version: v1
    spec:
      containers:
        - name: flaskapp
          image: dustise/flaskapp
          imagePullPolicy: IfNotPresent
---
